gbifstats.settings:
  type: config_object
  label: 'GBIF Stats settings'
  mapping:
    gbifstats:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'GBIF Stats generator page title :'
        country_code:
          type: text
          label: 'Code on two letter of a country to getting data from GBIF API :'
block.settings.gbifstats_block:
  type: block_settings
  label: 'GBIF Stats block'
  mapping:
    gbifstats_block_settings:
      type: text
      label: 'GBIF Stats block settings'